### ISSUE TITLE
SIGETRM during shutdown forces shutdown

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1623]
When skaled is shutting down by internal cause, it counts this event as though it was external SIGTERM. This leads to forced shutdown if real SIGTERM is received during shutdown procedure. Need not to count internal exit request as SIGTERM.

**Comment by DmytroNazarenko** [comment]
skaled: 3.18.0-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
skaled: 3.18.0-beta.1


Cases:

- [x]  Node rotation  
- [x] State root mismatch error 
- [ ]  Consensus inactive timeout (3 hours)
- [ ]  Attached volume issues (no space left on the device)


Node Rotation
```
[2024-02-13 16:41:47.953] [6:consensus] [info] 29320:Consensus exiting: exitGracefully called by skaled
Internal exit initiated. Signal -1. Unknown signal type.
[2024-02-13 16:41:48.155] [config] [info] Node exit called
```

State root mismatch error
```
2024-02-14 15:00:34.099364   FATAL STATE ROOT MISMATCH ERROR: current state root 30...58 is not equal to arrived state root 32...67 with block ID #35386, /data_dir cleanup is recommended, exiting with code 200...

Internal exit initiated. Signal -1. Unknown signal type.
[2024-02-14 15:00:34.366] [6:main] [info] 35385:Exiting on block boundary for block 35385
```

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network
skaled: 3.18.0-beta.1

Consensus shutdown will be fixed in a separate issue https://github.com/skalenetwork/skale-consensus/issues/812
