### ISSUE TITLE
Update skaled to be fully compatible with latest ETH fork

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skaled#1736]
skaled hasn't been updated to the latest fork in years that cause differences in gas usage for txns and blocks and absence of some of the features (like `accessList` or `withdrawalList`). need to document and implement the changes needed to be done in order to be fully compatible with latest fork
```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/skaled/issues/1719
- [ ] https://github.com/skalenetwork/skaled/issues/1744
- [ ] https://github.com/skalenetwork/internal-support/issues/882
- [ ] https://github.com/skalenetwork/skaled/issues/1792
```
