### ISSUE TITLE
Investigate the discrepancy of latest Eth fork and skaled config

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skaled#1792]
add to skaled all the forks that were introduced since Istanbul fork. add all the features introduced in these forks and updated opcodes pricing
```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/skaled/issues/1793
- [ ] https://github.com/skalenetwork/skaled/issues/1794
- [ ] https://github.com/skalenetwork/skaled/issues/1795
- [ ] https://github.com/skalenetwork/skaled/issues/1796
- [ ] https://github.com/skalenetwork/skaled/issues/1912
- [ ] https://github.com/skalenetwork/skaled/issues/2347
- [ ] https://github.com/skalenetwork/skaled/issues/2348
```

**Comment by olehnikolaiev** [comment]
berlin fork  https://ethereum.org/history#berlin

london fork  https://ethereum.org/history#london

paris fork  https://ethereum.org/history#paris

shangai fork  https://ethereum.org/history#shanghai

cancun fork https://ethereum.org/en/history/#cancun

pektra fork https://ethereum.org/history#pektra

fusaka fork https://ethereum.org/history#fusaka

**Comment by PolinaKiporenko** [comment]
only research the differences during 2.5 and create a comprehensive document
