### ISSUE TITLE
Flexible deployment permissions

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/skaled#1876]
PRD LINK - https://www.notion.so/skalelabs/PRD-New-deployer-management-0a6a6456f8354a568c33fbc564ab6d3c?d=513c58740f0e4bd4a27dd705107c2321#a2a6936edaff46ed8459268256ed1935

### Problem

Due to permission limitations on SKALE chains(when free contract deployment is turned off) only specific users allowed to deploy and all the contracts. Create2Factory and other factories become a most wanted tools by wallets/sdks/developers. So to follow the trend we need to make limitations to these factories.

### Solution

Add mapping with permissions who can deploy through this contract and functions to manage this mapping.

And add isAddressWhitelist function which would support tx.origin and msg.sender params.
```[tasklist]
### Tasks
- [x] Modify skaled to pass 2 params
- [x] Modify ConfigController to accept 2 params for AddressWhitelisted
- [ ] https://github.com/skalenetwork/skaled/issues/1879
```

**Comment by payvint** [comment]
First draft version of updated ConfigController

```
// SPDX-License-Identifier: GPL-3.0

pragma solidity ˆ0.8.9;
import "@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/AccessControlEnumerableUpgradeable.sol";

contract ConfigController is AccessControlEnumerableUpgradeable {
    bytes32 public constant DEPLOYER_ADMIN_ROLE = keccak256("DEPLOYER_ADMIN_ROLE");
    bytes32 public constant DEPLOYER_ROLE = keccak256("DEPLOYER_ROLE");
    bytes32 public constant MTM_ADMIN_ROLE = keccak256("MTM_ADMIN_ROLE");
    bytes32 public constant PERMISSION_ADMIN_ROLE = keccak256("PERMISSION_ADMIN_ROLE");
    bool multiTransactionMode;
    bool freeContractDeployment;
    string public version;

    struct Permission {
        bool check;
        address admin;
        mapping(address => bool) whitelist;
    }

    mapping(address => Permission) public permissions;

    function enableMTM() external {
        require(hasRole(MTM_ADMIN_ROLE, msg.sender), "Caller is not an admin");
        require(!multiTransactionMode, "MultiTransactionMode is already enabled");
        multiTransactionMode = true;
    }

    function disableMTM() external {
        require(hasRole(MTM_ADMIN_ROLE, msg.sender), "Caller is not an admin");
        require(multiTransactionMode, "MultiTransactionMode is already disabled");
        multiTransactionMode = false;
    }

    function enableFreeContractDeployment() external {
        require(hasRole(DEPLOYER_ADMIN_ROLE, msg.sender), "Caller is not an admin");
        require(!freeContractDeployment, "Free contract deployment is already enabled");
        freeContractDeployment = true;
    }

    function disableFreeContractDeployment() external {
        require(hasRole(DEPLOYER_ADMIN_ROLE, msg.sender), "Caller is not an admin");
        require(freeContractDeployment, "Free contract deployment is already disabled");
        freeContractDeployment = false;
    }

    function addToWhitelist(address addr) external {
        grantRole(DEPLOYER_ROLE, addr);
    }

    function removeFromWhitelist(address addr) external {
        revokeRole(DEPLOYER_ROLE, addr);
    }

    function setVersion(string memory _version) external {
        require(hasRole(DEFAULT_ADMIN_ROLE, msg.sender), "Caller is not an admin");
        version = _version;
    }

    function setPermission(address sender, bool active) external {
        require(hasRole(PERMISSION_ADMIN_ROLE, msg.sender), "Caller is not an admin");
        permissions[sender].check = active;
    }

    function setPermissionAdmin(address sender, address admin) external {
        require(hasRole(PERMISSION_ADMIN_ROLE, msg.sender), "Caller is not an admin");
        permissions[sender].admin = admin;
    }

    function addPermission(address origin, address sender) external {
        require(
            msg.sender == permissions[sender].admin ||
            hasRole(PERMISSION_ADMIN_ROLE, msg.sender),
            "Caller is not an admin"
        );
        permissions[sender].whitelist[origin] = true;
    }

    function removePermission(address origin, address sender) external {
        require(
            msg.sender == permissions[sender].admin ||
            hasRole(PERMISSION_ADMIN_ROLE, msg.sender),
            "Caller is not an admin"
        );
        permissions[sender].whitelist[origin] = false;
    }

    function isAddressWhitelisted(address addr) external view returns (bool) {
        if (freeContractDeployment) {
            return true;
        }
        return hasRole(DEPLOYER_ROLE, addr) || AddressUpgradeable.isContract(addr);
    }

    function isAddressWhitelisted(address origin, address sender) external view returns (bool) {
        if (freeContractDeployment) {
            return true;
        }
        return 
            hasRole(DEPLOYER_ROLE, origin) ||
            hasRole(DEPLOYER_ROLE, sender) || 
            !permissions[sender].check ||
            permissions[sender].whitelist[origin];
    }

    function isMTMEnabled() external view returns (bool) {
        return multiTransactionMode;
    }

    function isFCDEnabled() external view returns (bool) {
        return freeContractDeployment;
    }
}
```

**Comment by PolinaKiporenko** [comment]
3.19.0-beta.0

**Comment by OleksanderSalamatov** [comment]
Skaled: 3.19.0-beta.1
config-controller: 1.1.0
Schain: submissive-well-off-rotanev
Network: Regression-2.4

Verified new logic on updated config-controller, need to verify that old logic is still working on chains with non-updated config-controller and task could be closed
```
No permissions 
0xf5ea7f25f06cae3187acb4e1063673fa726efd99c6d4b6bf06a0066e3f760c10 - failed - OK

FCD
0xb9a3fc053d204356a60bdc3b5008261825ae7b71a1ca7341ba45730bc7cd8daf - passed - OK  

origin has deployer role 
0xd1269a45baeeef5f01a16375be9a97397f640c5f5ae429ca1efce74c56af0b38 - passed - OK 

deployer has deployer role
0x429cc43a8631c504359fdf0efd671a857cca22899e61eefe542a22eabeabddc6 - passed - OK

allowOrigin
1. No allowed origin - 0xa03380c77fdddde0f2e66d1f20bf6ce03cbf726efe8d0a580d60ad59f3a405e6 - failed - OK
2. Allowed origin - 0x3425b63a865f041f5b7c72999121b86944f419ac27b77ee074c1c4378f3b5838 - passed - OK
3. Forbidden origin - 0x3cdb8cc72595f7d7d4eddc2c61ebf4253f6351776aaf33d23550f8fa6c6f66c6 - failed - OK
```

**Comment by OleksanderSalamatov** [comment]
Skaled: 3.19.0-beta.1
config-controller: 1.0.1.dev2
Schain: easy-going-eminent-sadr
Network: Regression-2.4

Verified that old logic still work
```
No permissions
0xde776dcd235b48aef80758caf111a1430a033963b3e57be284fb1aedd9c6b656 - failed - OK  

FCD
0xa199f8efa22f170631cfc4726f50980873276b2ab10cee591b7dbea7161d66fa - passed - OK  

Smart Contract
0x8e8a5e22b114dfd731499dac86a20a33badedf5fa2dd0067fd119dded9406cde - passed - OK 

Deployer role 
0x618a6faba6a156fa9b47a5967d4f8462e8efa701000ac496df7806e5f814fe18 - passed - OK
```
